### ISSUE TITLE
Issue: No suitable key found in keytab

### ISSUE THREAD

**Issue by aitzubi** [ubuntu/adsys#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Hi,

I have configured adsys and our Active Directory Certificate Services to autoenroll certificates in my Ubuntu 22.04 laptop. After reading the docs, I see that actually only Computer certificates are supported nowadays. I configured a GPO so that a computer certificate is issued to my laptop but it does not work. I get a RuntimeError('No suitable key found in keytab.').

I think that it is logical as I only have my domain users keys on the keytab. No machine key so far.

So, how can I get a certificate from ADCS using adsys? Or am I missing something?

Kind regards,

### Steps to reproduce it

1.- ADCS configured with CEP/CES services with Kerberos auth enabled.
2.- GPO configured to automatically issue certificates to adsys enabled laptops
3.- Certmonger, cepces and all related packages and dependencies are installed
4.- After running systemctl status certmonger.service, I get an Error: RuntimeError('No suitable key found in keytab.')

### Environment
* adsys version: 0.14.2~22.04~ppa2
* Distribution: Ubuntu 22.04.4 LTS
* Distribution version: 22.04.4 LTS (Jammy Jellyfish)

### Log files
Please redact/remove sensitive information:
```raw
2024-09-05 13:24:08,194 cepces.config.Configuration:DEBUG:Initializing application configuration.
2024-09-05 13:24:08,194 cepces.config.Configuration:DEBUG:Reading: /etc/cepces/cepces.conf
2024-09-05 13:24:08,195 cepces.auth.KerberosAuthenticationHandler<0x71e0770760e0>:DEBUG:Initializing cepces.auth.KerberosAuthenticationHandler<0x71e0770760e0>.
2024-09-05 13:24:08,195 cepces.soap.auth.TransportKerberosAuthentication<0x71e0770762c0>:DEBUG:Initializing cepces.soap.auth.TransportKerberosAuthentication<0x71e0770762c0>.
2024-09-05 13:24:08,196 cepces.krb5.core.Context<0x71e077076440>:DEBUG:Initializing cepces.krb5.core.Context<0x71e077076440>.
2024-09-05 13:24:08,196 cepces.krb5.core.Context<0x71e077076440>:DEBUG:Handle <cepces.krb5.types.LP__krb5_context object at 0x71e076ff79c0>
2024-09-05 13:24:08,196 cepces.krb5.core.Keytab<0x71e077076590>:DEBUG:Initializing cepces.krb5.core.Keytab<0x71e077076590>.
2024-09-05 13:24:08,196 cepces.krb5.core.Keytab<0x71e077076590>:DEBUG:Handle <cepces.krb5.types.LP__krb5_kt object at 0x71e076ff7c40>
2024-09-05 13:24:08,196 cepces.krb5.core.KeytabName<0x71e077076620>:DEBUG:Initializing cepces.krb5.core.KeytabName<0x71e077076620>.
2024-09-05 13:24:08,196 cepces.krb5.core.KeytabName<0x71e077076620>:DEBUG:Handle None
2024-09-05 13:24:08,197 cepces.krb5.core.Principal<0x71e077076740>:DEBUG:Initializing cepces.krb5.core.Principal<0x71e077076740>.
2024-09-05 13:24:08,197 cepces.krb5.core.Principal<0x71e077076740>:DEBUG:Handle <cepces.krb5.types.LP_krb5_principal_data object at 0x71e076ff7dc0>
2024-09-05 13:24:08,197 cepces.krb5.core.PrincipalName<0x71e07703cee0>:DEBUG:Initializing cepces.krb5.core.PrincipalName<0x71e07703cee0>.
2024-09-05 13:24:08,197 cepces.krb5.core.PrincipalName<0x71e07703cee0>:DEBUG:Handle None
2024-09-05 13:24:08,198 cepces.krb5.core.CredentialOptions<0x71e077076770>:DEBUG:Initializing cepces.krb5.core.CredentialOptions<0x71e077076770>.
2024-09-05 13:24:08,198 cepces.krb5.core.CredentialOptions<0x71e077076770>:DEBUG:Handle <cepces.krb5.types.LP__krb5_get_init_creds_opt object at 0x71e076ff7cc0>
2024-09-05 13:24:08,198 cepces.krb5.core.Credentials<0x71e077075c00>:DEBUG:Initializing cepces.krb5.core.Credentials<0x71e077075c00>.
2024-09-05 13:24:08,198 cepces.krb5.core.Credentials<0x71e077075c00>:DEBUG:Handle <cepces.krb5.types._krb5_creds object at 0x71e076ff7e40>
2024-09-05 13:24:08,199 cepces.soap.auth.TransportKerberosAuthentication<0x71e07703cee0>:DEBUG:Initializing cepces.soap.auth.TransportKerberosAuthentication<0x71e07703cee0>.
2024-09-05 13:24:08,199 cepces.krb5.core.Context<0x71e077075a50>:DEBUG:Initializing cepces.krb5.core.Context<0x71e077075a50>.
2024-09-05 13:24:08,199 cepces.krb5.core.Context<0x71e077075a50>:DEBUG:Handle <cepces.krb5.types.LP__krb5_context object at 0x71e076ff7cc0>
2024-09-05 13:24:08,199 cepces.krb5.core.Keytab<0x71e077076740>:DEBUG:Initializing cepces.krb5.core.Keytab<0x71e077076740>.
2024-09-05 13:24:08,199 cepces.krb5.core.Keytab<0x71e077076740>:DEBUG:Handle <cepces.krb5.types.LP__krb5_kt object at 0x71e076ff7c40>
2024-09-05 13:24:08,199 cepces.krb5.core.KeytabName<0x71e077076590>:DEBUG:Initializing cepces.krb5.core.KeytabName<0x71e077076590>.
2024-09-05 13:24:08,199 cepces.krb5.core.KeytabName<0x71e077076590>:DEBUG:Handle None
2024-09-05 13:24:08,200 cepces.krb5.core.Principal<0x71e077076680>:DEBUG:Initializing cepces.krb5.core.Principal<0x71e077076680>.
2024-09-05 13:24:08,200 cepces.krb5.core.Principal<0x71e077076680>:DEBUG:Handle <cepces.krb5.types.LP_krb5_principal_data object at 0x71e076ff7dc0>
2024-09-05 13:24:08,200 cepces.krb5.core.PrincipalName<0x71e077075bd0>:DEBUG:Initializing cepces.krb5.core.PrincipalName<0x71e077075bd0>.
2024-09-05 13:24:08,200 cepces.krb5.core.PrincipalName<0x71e077075bd0>:DEBUG:Handle None
2024-09-05 13:24:08,200 cepces.krb5.core.CredentialOptions<0x71e077075c00>:DEBUG:Initializing cepces.krb5.core.CredentialOptions<0x71e077075c00>.
2024-09-05 13:24:08,200 cepces.krb5.core.CredentialOptions<0x71e077075c00>:DEBUG:Handle <cepces.krb5.types.LP__krb5_get_init_creds_opt object at 0x71e076ff7e40>
2024-09-05 13:24:08,200 cepces.krb5.core.Credentials<0x71e0770759c0>:DEBUG:Initializing cepces.krb5.core.Credentials<0x71e0770759c0>.
2024-09-05 13:24:08,200 cepces.krb5.core.Credentials<0x71e0770759c0>:DEBUG:Handle <cepces.krb5.types._krb5_creds object at 0x71e076ff7ec0>
2024-09-05 13:24:08,201 cepces.soap.auth.TransportKerberosAuthentication<0x71e07703cee0>:DEBUG:Initializing cepces.soap.auth.TransportKerberosAuthentication<0x71e07703cee0>.
2024-09-05 13:24:08,201 cepces.krb5.core.Context<0x71e0770768c0>:DEBUG:Initializing cepces.krb5.core.Context<0x71e0770768c0>.
2024-09-05 13:24:08,201 cepces.krb5.core.Context<0x71e0770768c0>:DEBUG:Handle <cepces.krb5.types.LP__krb5_context object at 0x71e076ff7cc0>
2024-09-05 13:24:08,201 cepces.krb5.core.Keytab<0x71e077076680>:DEBUG:Initializing cepces.krb5.core.Keytab<0x71e077076680>.
2024-09-05 13:24:08,201 cepces.krb5.core.Keytab<0x71e077076680>:DEBUG:Handle <cepces.krb5.types.LP__krb5_kt object at 0x71e076ff7dc0>
2024-09-05 13:24:08,201 cepces.krb5.core.KeytabName<0x71e077075c60>:DEBUG:Initializing cepces.krb5.core.KeytabName<0x71e077075c60>.
2024-09-05 13:24:08,201 cepces.krb5.core.KeytabName<0x71e077075c60>:DEBUG:Handle None
2024-09-05 13:24:08,201 cepces.krb5.core.Principal<0x71e077076590>:DEBUG:Initializing cepces.krb5.core.Principal<0x71e077076590>.
2024-09-05 13:24:08,201 cepces.krb5.core.Principal<0x71e077076590>:DEBUG:Handle <cepces.krb5.types.LP_krb5_principal_data object at 0x71e076ff7e40>
2024-09-05 13:24:08,202 cepces.krb5.core.PrincipalName<0x71e0770762c0>:DEBUG:Initializing cepces.krb5.core.PrincipalName<0x71e0770762c0>.
2024-09-05 13:24:08,202 cepces.krb5.core.PrincipalName<0x71e0770762c0>:DEBUG:Handle None
2024-09-05 13:24:08,202 cepces.krb5.core.CredentialOptions<0x71e077076620>:DEBUG:Initializing cepces.krb5.core.CredentialOptions<0x71e077076620>.
2024-09-05 13:24:08,202 cepces.krb5.core.CredentialOptions<0x71e077076620>:DEBUG:Handle <cepces.krb5.types.LP__krb5_get_init_creds_opt object at 0x71e076ff7c40>
2024-09-05 13:24:08,202 cepces.krb5.core.Credentials<0x71e077076830>:DEBUG:Initializing cepces.krb5.core.Credentials<0x71e077076830>.
2024-09-05 13:24:08,202 cepces.krb5.core.Credentials<0x71e077076830>:DEBUG:Handle <cepces.krb5.types._krb5_creds object at 0x71e076ff7ec0>
2024-09-05 13:24:08,202 cepces.soap.auth.TransportKerberosAuthentication<0x71e07703cee0>:DEBUG:Initializing cepces.soap.auth.TransportKerberosAuthentication<0x71e07703cee0>.
2024-09-05 13:24:08,203 cepces.krb5.core.Context<0x71e077075300>:DEBUG:Initializing cepces.krb5.core.Context<0x71e077075300>.
2024-09-05 13:24:08,203 cepces.krb5.core.Context<0x71e077075300>:DEBUG:Handle <cepces.krb5.types.LP__krb5_context object at 0x71e076ff7cc0>
2024-09-05 13:24:08,203 cepces.krb5.core.Keytab<0x71e077076590>:DEBUG:Initializing cepces.krb5.core.Keytab<0x71e077076590>.
2024-09-05 13:24:08,203 cepces.krb5.core.Keytab<0x71e077076590>:DEBUG:Handle <cepces.krb5.types.LP__krb5_kt object at 0x71e076ff7e40>
2024-09-05 13:24:08,203 cepces.krb5.core.KeytabName<0x71e0770762c0>:DEBUG:Initializing cepces.krb5.core.KeytabName<0x71e0770762c0>.
2024-09-05 13:24:08,203 cepces.krb5.core.KeytabName<0x71e0770762c0>:DEBUG:Handle None
2024-09-05 13:24:08,203 cepces.krb5.core.Principal<0x71e077075bd0>:DEBUG:Initializing cepces.krb5.core.Principal<0x71e077075bd0>.
2024-09-05 13:24:08,204 cepces.krb5.core.Principal<0x71e077075bd0>:DEBUG:Handle <cepces.krb5.types.LP_krb5_principal_data object at 0x71e076ff7c40>
2024-09-05 13:24:08,204 cepces.krb5.core.PrincipalName<0x71e077076890>:DEBUG:Initializing cepces.krb5.core.PrincipalName<0x71e077076890>.
2024-09-05 13:24:08,204 cepces.krb5.core.PrincipalName<0x71e077076890>:DEBUG:Handle None
2024-09-05 13:24:08,204 cepces.krb5.core.CredentialOptions<0x71e077075c60>:DEBUG:Initializing cepces.krb5.core.CredentialOptions<0x71e077075c60>.
2024-09-05 13:24:08,204 cepces.krb5.core.CredentialOptions<0x71e077075c60>:DEBUG:Handle <cepces.krb5.types.LP__krb5_get_init_creds_opt object at 0x71e076ff7dc0>
2024-09-05 13:24:08,204 cepces.krb5.core.Credentials<0x71e077076a10>:DEBUG:Initializing cepces.krb5.core.Credentials<0x71e077076a10>.
2024-09-05 13:24:08,204 cepces.krb5.core.Credentials<0x71e077076a10>:DEBUG:Handle <cepces.krb5.types._krb5_creds object at 0x71e076ff7ec0>
2024-09-05 13:24:08,205 __main__:ERROR:Traceback (most recent call last):
  File "/usr/libexec/certmonger/cepces-submit", line 64, in main
    config = Configuration.load(global_overrides=global_overrides,
  File "/usr/lib/python3/dist-packages/cepces/config.py", line 156, in load
    return Configuration.from_parser(config)
  File "/usr/lib/python3/dist-packages/cepces/config.py", line 196, in from_parser
    return Configuration(endpoint, endpoint_type, cas, authn.handle(), poll_interval, openssl_seclevel)
  File "/usr/lib/python3/dist-packages/cepces/auth.py", line 100, in handle
    raise RuntimeError('No suitable key found in keytab.')
RuntimeError: No suitable key found in keytab.

```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by aitzubi** [comment]
OK, I found the issue.

First of all, your IIS server for CEP / CES must be configured to use Negotiate:Kerberos as the provider. You should also uncheck the Kernel mode authentication. All of this on each CEP / CES folder authentication settings on your IIS. A good tutorial on how to install this: https://www.vkernel.ro/blog/installing-and-configuring-cep-and-ces-for-certificate-enrolling-on-non-domain-joined-computers

Second issue. After configuring this, the keytab issue was gone but I was unable to get any certificates issued by the CA. Certmonger was complaining with 'status: CA_UNCONFIGURED' error on a cert that was being monitorized. After much troubleshooting, I found out that it only works if the the certificate template on ADCS has the compatibility level at Windows Server 2008. If you use a template with compatibility level 2012 or greater it does not work.

I leave this commet for future reference and hoping that it would help someone.

@denisonbarbosa as you helped me with the other issue, I ping you so you can update your docs with this info. If I can help please feel free to ask.

Kind regards,

**Comment by jibel** [comment]
Thanks for following up @aitzubi and the additional information you provided. We will update the docs accordingly.

**Comment by aitzubi** [comment]
Thanks to yo @jibel ! Feel free to reach out if you need screenshots or any kind of info. My tests where done to a Windows 2019 server with ADCS and IIS 10.0 installed.
